
pomodoro: main.c db16.h db16.c screen.h screen.c display.h display.c buttons.h buttons.c 
	cc -Wall -pedantic -std=c11 -ggdb -I /Library/Frameworks/SDL2.framework/Headers -framework SDL2 main.c db16.c screen.c display.c buttons.c -o pomodoro
